//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATK.SpellerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpellerErrorCode", Namespace="http://nlptoolkit.cloudapp.net")]
    public enum SpellerErrorCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorNonInitialized = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorAccessDenied = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorQuotaExceeded = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorAuthintication = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorMaxLengthExceeded = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorUnknown = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorInvalidMode = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorInvalidParameter = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorDataFileNotFound = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorFailedToLoadData = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorFailedToSaveData = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorInsufficientResources = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorSarfDllMissing = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorFastMorphFailedToLoad = 14,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErroneousWord", Namespace="http://nlptoolkit.cloudapp.net")]
    [System.SerializableAttribute()]
    public partial class ErroneousWord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ATK.SpellerService.Correction[] CorrectionsField;
        
        private int PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ATK.SpellerService.Correction[] Corrections {
            get {
                return this.CorrectionsField;
            }
            set {
                if ((object.ReferenceEquals(this.CorrectionsField, value) != true)) {
                    this.CorrectionsField = value;
                    this.RaisePropertyChanged("Corrections");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Position {
            get {
                return this.PositionField;
            }
            set {
                if ((this.PositionField.Equals(value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Word {
            get {
                return this.WordField;
            }
            set {
                if ((object.ReferenceEquals(this.WordField, value) != true)) {
                    this.WordField = value;
                    this.RaisePropertyChanged("Word");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Correction", Namespace="http://nlptoolkit.cloudapp.net")]
    [System.SerializableAttribute()]
    public partial class Correction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorrectionTextField;
        
        private ATK.SpellerService.CorrectionType CorrectionTypeField;
        
        private int PositionInCorrectedTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CorrectionText {
            get {
                return this.CorrectionTextField;
            }
            set {
                if ((object.ReferenceEquals(this.CorrectionTextField, value) != true)) {
                    this.CorrectionTextField = value;
                    this.RaisePropertyChanged("CorrectionText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ATK.SpellerService.CorrectionType CorrectionType {
            get {
                return this.CorrectionTypeField;
            }
            set {
                if ((this.CorrectionTypeField.Equals(value) != true)) {
                    this.CorrectionTypeField = value;
                    this.RaisePropertyChanged("CorrectionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PositionInCorrectedText {
            get {
                return this.PositionInCorrectedTextField;
            }
            set {
                if ((this.PositionInCorrectedTextField.Equals(value) != true)) {
                    this.PositionInCorrectedTextField = value;
                    this.RaisePropertyChanged("PositionInCorrectedText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CorrectionType", Namespace="http://nlptoolkit.cloudapp.net")]
    public enum CorrectionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CORRECTION_TYPE_AUTO = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CORRECTION_TYPE_SPELLING = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CORRECTION_TYPE_CONTEXTUAL = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SuggestionOption", Namespace="http://nlptoolkit.cloudapp.net")]
    public enum SuggestionOption : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AutoCorrections = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SpellingCorrections = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AllCorrections = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nlptoolkit.cloudapp.net", ConfigurationName="SpellerService.ISpellerService")]
    public interface ISpellerService {
        
        // CODEGEN: Generating message contract since element name appId from namespace http://nlptoolkit.cloudapp.net is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/DetectMistakes", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/DetectMistakesResponse")]
        ATK.SpellerService.DetectMistakesResponse DetectMistakes(ATK.SpellerService.DetectMistakesRequest request);
        
        // CODEGEN: Generating message contract since element name appId from namespace http://nlptoolkit.cloudapp.net is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/SuggestCorrections", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/SuggestCorrectionsResponse")]
        ATK.SpellerService.SuggestCorrectionsResponse SuggestCorrections(ATK.SpellerService.SuggestCorrectionsRequest request);
        
        // CODEGEN: Generating message contract since element name appId from namespace http://nlptoolkit.cloudapp.net is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/ReportCorrectionSelection", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/ReportCorrectionSelectionResponse")]
        ATK.SpellerService.ReportCorrectionSelectionResponse ReportCorrectionSelection(ATK.SpellerService.ReportCorrectionSelectionRequest request);
        
        // CODEGEN: Generating message contract since element name appId from namespace http://nlptoolkit.cloudapp.net is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/SuggestCorrectionForSpecificWord", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/SuggestCorrectionForSpecificWordRe" +
            "sponse")]
        ATK.SpellerService.SuggestCorrectionForSpecificWordResponse SuggestCorrectionForSpecificWord(ATK.SpellerService.SuggestCorrectionForSpecificWordRequest request);
        
        // CODEGEN: Generating message contract since element name appId from namespace http://nlptoolkit.cloudapp.net is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/Autocorrect", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/AutocorrectResponse")]
        ATK.SpellerService.AutocorrectResponse Autocorrect(ATK.SpellerService.AutocorrectRequest request);
        
        // CODEGEN: Generating message contract since element name appId from namespace http://nlptoolkit.cloudapp.net is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/AutocorrectAndSuggest", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/AutocorrectAndSuggestResponse")]
        ATK.SpellerService.AutocorrectAndSuggestResponse AutocorrectAndSuggest(ATK.SpellerService.AutocorrectAndSuggestRequest request);
        
        // CODEGEN: Generating message contract since element name appId from namespace http://nlptoolkit.cloudapp.net is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/AutocorrectAndSuggest2", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/AutocorrectAndSuggest2Response")]
        ATK.SpellerService.AutocorrectAndSuggest2Response AutocorrectAndSuggest2(ATK.SpellerService.AutocorrectAndSuggest2Request request);
        
        // CODEGEN: Generating message contract since element name appId from namespace http://nlptoolkit.cloudapp.net is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/ReportWronglyDetectedWord", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/ReportWronglyDetectedWordResponse")]
        ATK.SpellerService.ReportWronglyDetectedWordResponse ReportWronglyDetectedWord(ATK.SpellerService.ReportWronglyDetectedWordRequest request);
        
        // CODEGEN: Generating message contract since element name appId from namespace http://nlptoolkit.cloudapp.net is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/SuggestMissingCorrection", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/SuggestMissingCorrectionResponse")]
        ATK.SpellerService.SuggestMissingCorrectionResponse SuggestMissingCorrection(ATK.SpellerService.SuggestMissingCorrectionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DetectMistakesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DetectMistakes", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public ATK.SpellerService.DetectMistakesRequestBody Body;
        
        public DetectMistakesRequest() {
        }
        
        public DetectMistakesRequest(ATK.SpellerService.DetectMistakesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class DetectMistakesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string inText;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool processLastWordOnly;
        
        public DetectMistakesRequestBody() {
        }
        
        public DetectMistakesRequestBody(string appId, string inText, bool processLastWordOnly) {
            this.appId = appId;
            this.inText = inText;
            this.processLastWordOnly = processLastWordOnly;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DetectMistakesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DetectMistakesResponse", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public ATK.SpellerService.DetectMistakesResponseBody Body;
        
        public DetectMistakesResponse() {
        }
        
        public DetectMistakesResponse(ATK.SpellerService.DetectMistakesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class DetectMistakesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ATK.SpellerService.SpellerErrorCode DetectMistakesResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ATK.SpellerService.ErroneousWord[] erroneousWords;
        
        public DetectMistakesResponseBody() {
        }
        
        public DetectMistakesResponseBody(ATK.SpellerService.SpellerErrorCode DetectMistakesResult, ATK.SpellerService.ErroneousWord[] erroneousWords) {
            this.DetectMistakesResult = DetectMistakesResult;
            this.erroneousWords = erroneousWords;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuggestCorrectionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SuggestCorrections", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public ATK.SpellerService.SuggestCorrectionsRequestBody Body;
        
        public SuggestCorrectionsRequest() {
        }
        
        public SuggestCorrectionsRequest(ATK.SpellerService.SuggestCorrectionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class SuggestCorrectionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string inText;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ATK.SpellerService.SuggestionOption correctionOptions;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool processLastWordOnly;
        
        public SuggestCorrectionsRequestBody() {
        }
        
        public SuggestCorrectionsRequestBody(string appId, string inText, ATK.SpellerService.SuggestionOption correctionOptions, bool processLastWordOnly) {
            this.appId = appId;
            this.inText = inText;
            this.correctionOptions = correctionOptions;
            this.processLastWordOnly = processLastWordOnly;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuggestCorrectionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SuggestCorrectionsResponse", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public ATK.SpellerService.SuggestCorrectionsResponseBody Body;
        
        public SuggestCorrectionsResponse() {
        }
        
        public SuggestCorrectionsResponse(ATK.SpellerService.SuggestCorrectionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class SuggestCorrectionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ATK.SpellerService.SpellerErrorCode SuggestCorrectionsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ATK.SpellerService.ErroneousWord[] erroneousWords;
        
        public SuggestCorrectionsResponseBody() {
        }
        
        public SuggestCorrectionsResponseBody(ATK.SpellerService.SpellerErrorCode SuggestCorrectionsResult, ATK.SpellerService.ErroneousWord[] erroneousWords) {
            this.SuggestCorrectionsResult = SuggestCorrectionsResult;
            this.erroneousWords = erroneousWords;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReportCorrectionSelectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReportCorrectionSelection", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public ATK.SpellerService.ReportCorrectionSelectionRequestBody Body;
        
        public ReportCorrectionSelectionRequest() {
        }
        
        public ReportCorrectionSelectionRequest(ATK.SpellerService.ReportCorrectionSelectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class ReportCorrectionSelectionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string word;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string context;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string correction;
        
        public ReportCorrectionSelectionRequestBody() {
        }
        
        public ReportCorrectionSelectionRequestBody(string appId, string word, string context, string correction) {
            this.appId = appId;
            this.word = word;
            this.context = context;
            this.correction = correction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReportCorrectionSelectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReportCorrectionSelectionResponse", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public ATK.SpellerService.ReportCorrectionSelectionResponseBody Body;
        
        public ReportCorrectionSelectionResponse() {
        }
        
        public ReportCorrectionSelectionResponse(ATK.SpellerService.ReportCorrectionSelectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class ReportCorrectionSelectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ATK.SpellerService.SpellerErrorCode ReportCorrectionSelectionResult;
        
        public ReportCorrectionSelectionResponseBody() {
        }
        
        public ReportCorrectionSelectionResponseBody(ATK.SpellerService.SpellerErrorCode ReportCorrectionSelectionResult) {
            this.ReportCorrectionSelectionResult = ReportCorrectionSelectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuggestCorrectionForSpecificWordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SuggestCorrectionForSpecificWord", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public ATK.SpellerService.SuggestCorrectionForSpecificWordRequestBody Body;
        
        public SuggestCorrectionForSpecificWordRequest() {
        }
        
        public SuggestCorrectionForSpecificWordRequest(ATK.SpellerService.SuggestCorrectionForSpecificWordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class SuggestCorrectionForSpecificWordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string inText;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int wordPosition;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public ATK.SpellerService.SuggestionOption correctionOptions;
        
        public SuggestCorrectionForSpecificWordRequestBody() {
        }
        
        public SuggestCorrectionForSpecificWordRequestBody(string appId, string inText, int wordPosition, ATK.SpellerService.SuggestionOption correctionOptions) {
            this.appId = appId;
            this.inText = inText;
            this.wordPosition = wordPosition;
            this.correctionOptions = correctionOptions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuggestCorrectionForSpecificWordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SuggestCorrectionForSpecificWordResponse", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public ATK.SpellerService.SuggestCorrectionForSpecificWordResponseBody Body;
        
        public SuggestCorrectionForSpecificWordResponse() {
        }
        
        public SuggestCorrectionForSpecificWordResponse(ATK.SpellerService.SuggestCorrectionForSpecificWordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class SuggestCorrectionForSpecificWordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ATK.SpellerService.SpellerErrorCode SuggestCorrectionForSpecificWordResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ATK.SpellerService.ErroneousWord erroneousWord;
        
        public SuggestCorrectionForSpecificWordResponseBody() {
        }
        
        public SuggestCorrectionForSpecificWordResponseBody(ATK.SpellerService.SpellerErrorCode SuggestCorrectionForSpecificWordResult, ATK.SpellerService.ErroneousWord erroneousWord) {
            this.SuggestCorrectionForSpecificWordResult = SuggestCorrectionForSpecificWordResult;
            this.erroneousWord = erroneousWord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutocorrectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Autocorrect", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public ATK.SpellerService.AutocorrectRequestBody Body;
        
        public AutocorrectRequest() {
        }
        
        public AutocorrectRequest(ATK.SpellerService.AutocorrectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class AutocorrectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string inText;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool processLastWordOnly;
        
        public AutocorrectRequestBody() {
        }
        
        public AutocorrectRequestBody(string appId, string inText, bool processLastWordOnly) {
            this.appId = appId;
            this.inText = inText;
            this.processLastWordOnly = processLastWordOnly;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutocorrectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutocorrectResponse", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public ATK.SpellerService.AutocorrectResponseBody Body;
        
        public AutocorrectResponse() {
        }
        
        public AutocorrectResponse(ATK.SpellerService.AutocorrectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class AutocorrectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ATK.SpellerService.SpellerErrorCode AutocorrectResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string correctedText;
        
        public AutocorrectResponseBody() {
        }
        
        public AutocorrectResponseBody(ATK.SpellerService.SpellerErrorCode AutocorrectResult, string correctedText) {
            this.AutocorrectResult = AutocorrectResult;
            this.correctedText = correctedText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutocorrectAndSuggestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutocorrectAndSuggest", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public ATK.SpellerService.AutocorrectAndSuggestRequestBody Body;
        
        public AutocorrectAndSuggestRequest() {
        }
        
        public AutocorrectAndSuggestRequest(ATK.SpellerService.AutocorrectAndSuggestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class AutocorrectAndSuggestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string inText;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool processLastWordOnly;
        
        public AutocorrectAndSuggestRequestBody() {
        }
        
        public AutocorrectAndSuggestRequestBody(string appId, string inText, bool processLastWordOnly) {
            this.appId = appId;
            this.inText = inText;
            this.processLastWordOnly = processLastWordOnly;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutocorrectAndSuggestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutocorrectAndSuggestResponse", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public ATK.SpellerService.AutocorrectAndSuggestResponseBody Body;
        
        public AutocorrectAndSuggestResponse() {
        }
        
        public AutocorrectAndSuggestResponse(ATK.SpellerService.AutocorrectAndSuggestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class AutocorrectAndSuggestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ATK.SpellerService.SpellerErrorCode AutocorrectAndSuggestResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string correctedText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ATK.SpellerService.ErroneousWord[] erroneousWords;
        
        public AutocorrectAndSuggestResponseBody() {
        }
        
        public AutocorrectAndSuggestResponseBody(ATK.SpellerService.SpellerErrorCode AutocorrectAndSuggestResult, string correctedText, ATK.SpellerService.ErroneousWord[] erroneousWords) {
            this.AutocorrectAndSuggestResult = AutocorrectAndSuggestResult;
            this.correctedText = correctedText;
            this.erroneousWords = erroneousWords;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutocorrectAndSuggest2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutocorrectAndSuggest2", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public ATK.SpellerService.AutocorrectAndSuggest2RequestBody Body;
        
        public AutocorrectAndSuggest2Request() {
        }
        
        public AutocorrectAndSuggest2Request(ATK.SpellerService.AutocorrectAndSuggest2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class AutocorrectAndSuggest2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string inText;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ATK.SpellerService.SuggestionOption correctionOptions;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool processLastWordOnly;
        
        public AutocorrectAndSuggest2RequestBody() {
        }
        
        public AutocorrectAndSuggest2RequestBody(string appId, string inText, ATK.SpellerService.SuggestionOption correctionOptions, bool processLastWordOnly) {
            this.appId = appId;
            this.inText = inText;
            this.correctionOptions = correctionOptions;
            this.processLastWordOnly = processLastWordOnly;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutocorrectAndSuggest2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutocorrectAndSuggest2Response", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public ATK.SpellerService.AutocorrectAndSuggest2ResponseBody Body;
        
        public AutocorrectAndSuggest2Response() {
        }
        
        public AutocorrectAndSuggest2Response(ATK.SpellerService.AutocorrectAndSuggest2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class AutocorrectAndSuggest2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ATK.SpellerService.SpellerErrorCode AutocorrectAndSuggest2Result;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string correctedText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ATK.SpellerService.ErroneousWord[] erroneousWords;
        
        public AutocorrectAndSuggest2ResponseBody() {
        }
        
        public AutocorrectAndSuggest2ResponseBody(ATK.SpellerService.SpellerErrorCode AutocorrectAndSuggest2Result, string correctedText, ATK.SpellerService.ErroneousWord[] erroneousWords) {
            this.AutocorrectAndSuggest2Result = AutocorrectAndSuggest2Result;
            this.correctedText = correctedText;
            this.erroneousWords = erroneousWords;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReportWronglyDetectedWordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReportWronglyDetectedWord", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public ATK.SpellerService.ReportWronglyDetectedWordRequestBody Body;
        
        public ReportWronglyDetectedWordRequest() {
        }
        
        public ReportWronglyDetectedWordRequest(ATK.SpellerService.ReportWronglyDetectedWordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class ReportWronglyDetectedWordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string word;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string context;
        
        public ReportWronglyDetectedWordRequestBody() {
        }
        
        public ReportWronglyDetectedWordRequestBody(string appId, string word, string context) {
            this.appId = appId;
            this.word = word;
            this.context = context;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReportWronglyDetectedWordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReportWronglyDetectedWordResponse", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public ATK.SpellerService.ReportWronglyDetectedWordResponseBody Body;
        
        public ReportWronglyDetectedWordResponse() {
        }
        
        public ReportWronglyDetectedWordResponse(ATK.SpellerService.ReportWronglyDetectedWordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class ReportWronglyDetectedWordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ATK.SpellerService.SpellerErrorCode ReportWronglyDetectedWordResult;
        
        public ReportWronglyDetectedWordResponseBody() {
        }
        
        public ReportWronglyDetectedWordResponseBody(ATK.SpellerService.SpellerErrorCode ReportWronglyDetectedWordResult) {
            this.ReportWronglyDetectedWordResult = ReportWronglyDetectedWordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuggestMissingCorrectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SuggestMissingCorrection", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public ATK.SpellerService.SuggestMissingCorrectionRequestBody Body;
        
        public SuggestMissingCorrectionRequest() {
        }
        
        public SuggestMissingCorrectionRequest(ATK.SpellerService.SuggestMissingCorrectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class SuggestMissingCorrectionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string word;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string context;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string correction;
        
        public SuggestMissingCorrectionRequestBody() {
        }
        
        public SuggestMissingCorrectionRequestBody(string appId, string word, string context, string correction) {
            this.appId = appId;
            this.word = word;
            this.context = context;
            this.correction = correction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuggestMissingCorrectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SuggestMissingCorrectionResponse", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public ATK.SpellerService.SuggestMissingCorrectionResponseBody Body;
        
        public SuggestMissingCorrectionResponse() {
        }
        
        public SuggestMissingCorrectionResponse(ATK.SpellerService.SuggestMissingCorrectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class SuggestMissingCorrectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ATK.SpellerService.SpellerErrorCode SuggestMissingCorrectionResult;
        
        public SuggestMissingCorrectionResponseBody() {
        }
        
        public SuggestMissingCorrectionResponseBody(ATK.SpellerService.SpellerErrorCode SuggestMissingCorrectionResult) {
            this.SuggestMissingCorrectionResult = SuggestMissingCorrectionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISpellerServiceChannel : ATK.SpellerService.ISpellerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SpellerServiceClient : System.ServiceModel.ClientBase<ATK.SpellerService.ISpellerService>, ATK.SpellerService.ISpellerService {
        
        public SpellerServiceClient() {
        }
        
        public SpellerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SpellerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpellerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpellerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATK.SpellerService.DetectMistakesResponse ATK.SpellerService.ISpellerService.DetectMistakes(ATK.SpellerService.DetectMistakesRequest request) {
            return base.Channel.DetectMistakes(request);
        }
        
        public ATK.SpellerService.SpellerErrorCode DetectMistakes(string appId, string inText, bool processLastWordOnly, out ATK.SpellerService.ErroneousWord[] erroneousWords) {
            ATK.SpellerService.DetectMistakesRequest inValue = new ATK.SpellerService.DetectMistakesRequest();
            inValue.Body = new ATK.SpellerService.DetectMistakesRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.inText = inText;
            inValue.Body.processLastWordOnly = processLastWordOnly;
            ATK.SpellerService.DetectMistakesResponse retVal = ((ATK.SpellerService.ISpellerService)(this)).DetectMistakes(inValue);
            erroneousWords = retVal.Body.erroneousWords;
            return retVal.Body.DetectMistakesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATK.SpellerService.SuggestCorrectionsResponse ATK.SpellerService.ISpellerService.SuggestCorrections(ATK.SpellerService.SuggestCorrectionsRequest request) {
            return base.Channel.SuggestCorrections(request);
        }
        
        public ATK.SpellerService.SpellerErrorCode SuggestCorrections(string appId, string inText, ATK.SpellerService.SuggestionOption correctionOptions, bool processLastWordOnly, out ATK.SpellerService.ErroneousWord[] erroneousWords) {
            ATK.SpellerService.SuggestCorrectionsRequest inValue = new ATK.SpellerService.SuggestCorrectionsRequest();
            inValue.Body = new ATK.SpellerService.SuggestCorrectionsRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.inText = inText;
            inValue.Body.correctionOptions = correctionOptions;
            inValue.Body.processLastWordOnly = processLastWordOnly;
            ATK.SpellerService.SuggestCorrectionsResponse retVal = ((ATK.SpellerService.ISpellerService)(this)).SuggestCorrections(inValue);
            erroneousWords = retVal.Body.erroneousWords;
            return retVal.Body.SuggestCorrectionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATK.SpellerService.ReportCorrectionSelectionResponse ATK.SpellerService.ISpellerService.ReportCorrectionSelection(ATK.SpellerService.ReportCorrectionSelectionRequest request) {
            return base.Channel.ReportCorrectionSelection(request);
        }
        
        public ATK.SpellerService.SpellerErrorCode ReportCorrectionSelection(string appId, string word, string context, string correction) {
            ATK.SpellerService.ReportCorrectionSelectionRequest inValue = new ATK.SpellerService.ReportCorrectionSelectionRequest();
            inValue.Body = new ATK.SpellerService.ReportCorrectionSelectionRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.word = word;
            inValue.Body.context = context;
            inValue.Body.correction = correction;
            ATK.SpellerService.ReportCorrectionSelectionResponse retVal = ((ATK.SpellerService.ISpellerService)(this)).ReportCorrectionSelection(inValue);
            return retVal.Body.ReportCorrectionSelectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATK.SpellerService.SuggestCorrectionForSpecificWordResponse ATK.SpellerService.ISpellerService.SuggestCorrectionForSpecificWord(ATK.SpellerService.SuggestCorrectionForSpecificWordRequest request) {
            return base.Channel.SuggestCorrectionForSpecificWord(request);
        }
        
        public ATK.SpellerService.SpellerErrorCode SuggestCorrectionForSpecificWord(string appId, string inText, int wordPosition, ATK.SpellerService.SuggestionOption correctionOptions, out ATK.SpellerService.ErroneousWord erroneousWord) {
            ATK.SpellerService.SuggestCorrectionForSpecificWordRequest inValue = new ATK.SpellerService.SuggestCorrectionForSpecificWordRequest();
            inValue.Body = new ATK.SpellerService.SuggestCorrectionForSpecificWordRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.inText = inText;
            inValue.Body.wordPosition = wordPosition;
            inValue.Body.correctionOptions = correctionOptions;
            ATK.SpellerService.SuggestCorrectionForSpecificWordResponse retVal = ((ATK.SpellerService.ISpellerService)(this)).SuggestCorrectionForSpecificWord(inValue);
            erroneousWord = retVal.Body.erroneousWord;
            return retVal.Body.SuggestCorrectionForSpecificWordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATK.SpellerService.AutocorrectResponse ATK.SpellerService.ISpellerService.Autocorrect(ATK.SpellerService.AutocorrectRequest request) {
            return base.Channel.Autocorrect(request);
        }
        
        public ATK.SpellerService.SpellerErrorCode Autocorrect(string appId, string inText, bool processLastWordOnly, out string correctedText) {
            ATK.SpellerService.AutocorrectRequest inValue = new ATK.SpellerService.AutocorrectRequest();
            inValue.Body = new ATK.SpellerService.AutocorrectRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.inText = inText;
            inValue.Body.processLastWordOnly = processLastWordOnly;
            ATK.SpellerService.AutocorrectResponse retVal = ((ATK.SpellerService.ISpellerService)(this)).Autocorrect(inValue);
            correctedText = retVal.Body.correctedText;
            return retVal.Body.AutocorrectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATK.SpellerService.AutocorrectAndSuggestResponse ATK.SpellerService.ISpellerService.AutocorrectAndSuggest(ATK.SpellerService.AutocorrectAndSuggestRequest request) {
            return base.Channel.AutocorrectAndSuggest(request);
        }
        
        public ATK.SpellerService.SpellerErrorCode AutocorrectAndSuggest(string appId, string inText, bool processLastWordOnly, out string correctedText, out ATK.SpellerService.ErroneousWord[] erroneousWords) {
            ATK.SpellerService.AutocorrectAndSuggestRequest inValue = new ATK.SpellerService.AutocorrectAndSuggestRequest();
            inValue.Body = new ATK.SpellerService.AutocorrectAndSuggestRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.inText = inText;
            inValue.Body.processLastWordOnly = processLastWordOnly;
            ATK.SpellerService.AutocorrectAndSuggestResponse retVal = ((ATK.SpellerService.ISpellerService)(this)).AutocorrectAndSuggest(inValue);
            correctedText = retVal.Body.correctedText;
            erroneousWords = retVal.Body.erroneousWords;
            return retVal.Body.AutocorrectAndSuggestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATK.SpellerService.AutocorrectAndSuggest2Response ATK.SpellerService.ISpellerService.AutocorrectAndSuggest2(ATK.SpellerService.AutocorrectAndSuggest2Request request) {
            return base.Channel.AutocorrectAndSuggest2(request);
        }
        
        public ATK.SpellerService.SpellerErrorCode AutocorrectAndSuggest2(string appId, string inText, ATK.SpellerService.SuggestionOption correctionOptions, bool processLastWordOnly, out string correctedText, out ATK.SpellerService.ErroneousWord[] erroneousWords) {
            ATK.SpellerService.AutocorrectAndSuggest2Request inValue = new ATK.SpellerService.AutocorrectAndSuggest2Request();
            inValue.Body = new ATK.SpellerService.AutocorrectAndSuggest2RequestBody();
            inValue.Body.appId = appId;
            inValue.Body.inText = inText;
            inValue.Body.correctionOptions = correctionOptions;
            inValue.Body.processLastWordOnly = processLastWordOnly;
            ATK.SpellerService.AutocorrectAndSuggest2Response retVal = ((ATK.SpellerService.ISpellerService)(this)).AutocorrectAndSuggest2(inValue);
            correctedText = retVal.Body.correctedText;
            erroneousWords = retVal.Body.erroneousWords;
            return retVal.Body.AutocorrectAndSuggest2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATK.SpellerService.ReportWronglyDetectedWordResponse ATK.SpellerService.ISpellerService.ReportWronglyDetectedWord(ATK.SpellerService.ReportWronglyDetectedWordRequest request) {
            return base.Channel.ReportWronglyDetectedWord(request);
        }
        
        public ATK.SpellerService.SpellerErrorCode ReportWronglyDetectedWord(string appId, string word, string context) {
            ATK.SpellerService.ReportWronglyDetectedWordRequest inValue = new ATK.SpellerService.ReportWronglyDetectedWordRequest();
            inValue.Body = new ATK.SpellerService.ReportWronglyDetectedWordRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.word = word;
            inValue.Body.context = context;
            ATK.SpellerService.ReportWronglyDetectedWordResponse retVal = ((ATK.SpellerService.ISpellerService)(this)).ReportWronglyDetectedWord(inValue);
            return retVal.Body.ReportWronglyDetectedWordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATK.SpellerService.SuggestMissingCorrectionResponse ATK.SpellerService.ISpellerService.SuggestMissingCorrection(ATK.SpellerService.SuggestMissingCorrectionRequest request) {
            return base.Channel.SuggestMissingCorrection(request);
        }
        
        public ATK.SpellerService.SpellerErrorCode SuggestMissingCorrection(string appId, string word, string context, string correction) {
            ATK.SpellerService.SuggestMissingCorrectionRequest inValue = new ATK.SpellerService.SuggestMissingCorrectionRequest();
            inValue.Body = new ATK.SpellerService.SuggestMissingCorrectionRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.word = word;
            inValue.Body.context = context;
            inValue.Body.correction = correction;
            ATK.SpellerService.SuggestMissingCorrectionResponse retVal = ((ATK.SpellerService.ISpellerService)(this)).SuggestMissingCorrection(inValue);
            return retVal.Body.SuggestMissingCorrectionResult;
        }
    }
}
